version: "3"
services:
    web:
        build:
            context: ./
            dockerfile: images/Dockerfile-nginx
        environment:
          - GA_PROPERTY_ID=foo
          - FIREBASE_ENDPOINT=somepath
          - FIREBASE_URL=mood
        ports:
            - "8040:80"
        volumes:
            - ./app:/app
            - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
