package com.smd.mood;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PathVariable;

import com.smd.mood.Mood;
import com.smd.mood.MoodRepository;

import java.util.Date;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/mood") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MoodRepository userRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam Integer mood) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Mood n = new Mood();
        n.setMood(mood);
        n.setCreatedDate(new Date(System.currentTimeMillis()));
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Mood> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}